### ISSUE TITLE
get option in functions.php

### ISSUE THREAD

**Issue by iografica** [gambitph/Titan-Framework#199]
if i try to get an option in the function.php of my custom theme (an example):

$titan = TitanFramework::getInstance( 'mythemename );
if ($titan->getOption('my_option')==true){
require get_template_directory() . '/inc/file.php';}

appear this error: 

Fatal error: Class 'TitanFramework' not found in /wordpress/wp-content/themes/mytheme/functions.php on line ...

Why? How can i solve?

**Comment by milojennings** [comment]
I've run into several situations where I needed to access options before `after_setup_theme`. I created this little function to serve that purpose:
```php
function get_titan_option($namespace, $option = null){
	$tf_options = get_option( $namespace . '_options' );
	$tf_options_unserialized = maybe_unserialize($tf_options);
	if($option){
		if(array_key_exists($option, $tf_options_unserialized))
			return $tf_options_unserialized[$option];
	}
	return null;
}
// usage
get_titan_option('dcf', 'fancy_option_thing');
```
