### ISSUE TITLE
Critical alerts - Theme Check

### ISSUE THREAD

**Issue by MichaelNagval** [gambitph/Titan-Framework#206]
Hi, thank you for awesome Titan! :)
I create my first WP theme and I check it
with http://themecheck.org and ThemeCheck
WP plugin. Everything is 
ok, only I receive critical alerts about some
Titan Framework files (screenshots)

I'm afraid to change something in core Titan
files and I want so much to solve these 
warnings, please dear author can you help
with that?

![theme_check](https://cloud.githubusercontent.com/assets/9263667/5539683/e15ba47a-8b0f-11e4-9b17-5357245805b0.jpg)

![themecheck2](https://cloud.githubusercontent.com/assets/9263667/5539641/7fd12c0c-8b0f-11e4-9510-516ab020eace.jpg)

**Comment by bfintal** [comment]
Use the `titan-framework-checker.php` instead of embedding the framework :)
