### ISSUE TITLE
Date Option "non well formed numeric value encountered"

### ISSUE THREAD

**Issue by jessor** [gambitph/Titan-Framework#207]
After adding the field to the configuration it showed the error

```A non well formed numeric value encountered in .../titan-framework/class-option-date.php on line 167```

After setting a date and saving it the notice disappears, also when the field is empty after that.

**Comment by bfintal** [comment]
It may be the default value for the option.

The `date` portion is formatted as `Y-m-d`, and the `time` portion is `H:i`

**Comment by ardalann** [comment]
I think this can be fixed by replacing line #53 in class-option-date.php:
``
if ( $value == '' ) {
``
with
``
if ( empty( $value ) ) {
``
