### ISSUE TITLE
gallery in metaboxes

### ISSUE THREAD

**Issue by sandrodz** [gambitph/Titan-Framework#213]
In issues I've read there was a talk about integrating draggable gallery meta box.

Is this implemented? cannot find anything related in docs.

**Comment by sandrodz** [comment]
Hello? is there anybody out there?

**Comment by trajche** [comment]
It's already been requested:
https://github.com/gambitph/Titan-Framework/issues/45

**Comment by sandrodz** [comment]
Hey, I was referring to that ticket.

The ticket #45 itself is unclear. Checkout this comment by bfintal:

"The image option has now been revamped to look like the animation @ provided above"
