### ISSUE TITLE
Duplicate descriptions

### ISSUE THREAD

**Issue by iografica** [gambitph/Titan-Framework#214]
Some descriptions in the customizer sections are duplicated (see checkbox and text filed descriptions). If i write the description for this two fields i see duplicated descriptions. It happen for online website, if i test the framework in a local machine it doesn't happen.

**Comment by andrewmclagan** [comment]
I have also seen this

**Comment by chetzof** [comment]
Confirm

**Comment by bfintal** [comment]
Closed in v1.8
