### ISSUE TITLE
Upload pdf,doc files

### ISSUE THREAD

**Issue by nayeem-ice10** [gambitph/Titan-Framework#215]
It seems that upload type works only with image, is there any way to upload other type of file like:pdf,doc ??

**Comment by ardalann** [comment]
Same issue here.

**Comment by ardalann** [comment]
Just added it in a pull request. You can test it out:
https://github.com/gambitph/Titan-Framework/pull/251

**Comment by ReggieDuran** [comment]
We've just merged file upload option. d93b7d8ea009732273d956584bcf0d0edb561517
