### ISSUE TITLE
get_terms instead of get_categories

### ISSUE THREAD

**Issue by trajche** [gambitph/Titan-Framework#216]
Hey - just wondering if there's any special reason that you used [get_categories](http://http://codex.wordpress.org/Function_Reference/get_categories) instead of [get_terms](http://codex.wordpress.org/Function_Reference/get_terms) ? I can try and modify select-categories or add a new one select-terms and do a pull request.

Some of the extra featured this allows:
- multiple taxonomies selected at once. for example, from one field one could pick between categories and tags
- returned fields, in this case id=>name is enough i believe
- name__like, search etc is possible

**Comment by ReggieDuran** [comment]
Sorry for taking this too long. 05c9309332cb0a4a5e6db28583a292fae6a4be5e
