### ISSUE TITLE
Missed options when upgrading Network (multisite)

### ISSUE THREAD

**Issue by leolweb** [gambitph/Titan-Framework#219]
I've encountered this problem with Wordpress 4.0 and above (currently I'm on 4.1.1), when I update network all sites options are missing.

Steps to reproduce:
- Update a Wordpress multisite installation from 4.x to the next available release
- Go to Upgrade Network (/wp-admin/network/upgrade.php)
- Click "Upgrade Network"

All options of all sites will be deleted.

I tested the same upgrade with other option frameworks without problems.

There is also a problem in class-titan-framework.php (line 190-193), in some conditions of save/retrieve is necessary to maybe_unserialize instead a direct unserialize of data.

**Comment by bfintal** [comment]
This was (i think) caused by TF saving default values in the database. This is removed in v1.9 so there shouldn't any be any issues now.
