### ISSUE TITLE
namespace and structure

### ISSUE THREAD

**Issue by andrewmclagan** [gambitph/Titan-Framework#220]
I would suggest namespacing all the classes as per modern development practices dictate for better code organisation.

/titan-framework
    /Option
      SelectPosts.php
      SelectPages.php
      SelectCategories.php
      ...
   /Container
      MetaBox.php
      ThemeCustomizer.php
      AdminPanel.php
   /Support
      FunctionUtil.php
      FrameworkChecker.php
      FrameworkEmbedder.php
      ...

Why? 
* no problem with class name conflicts. 
* In sync with modern best practices and the PSR standards.  
* better code organisation

Organising code in by naming files `class-name-like-this.php` is PHP from the `90's, its hard to sift through 40 PHP files and maintain the codebase. 

Im willing to write out a PR for this if you want?

**Comment by technosailor** [comment]
Namespaces break PHP < 5.3. WordPress core requirements are PHP 5.2.4. You can be a purist, or you can be incompatible with a possibly significant percentage of the WP core base.

**Comment by andrewmclagan** [comment]
pfff wordmess
