### ISSUE TITLE
Allow custom editor styles

### ISSUE THREAD

**Issue by SiamKreative** [gambitph/Titan-Framework#223]
Hi Benjamin,

It'd be awesome if you could add a new parameter to your [editor option](http://www.titanframework.net/editor-option/): use a custom stylesheet inside a TinyMCE editor. I'm referring to the function [add_editor_style](http://codex.wordpress.org/Function_Reference/add_editor_style). I'd like to be able to style elements inside tinyMCE.

Cheers

**Comment by bfintal** [comment]
I've added a `editor_settings` attribute to the editor option.

Now you can do this (similar to add_editor_style):

    'editor_settings' => array(
        'tinymce' => array(
            'content_css' => 'path/to/editor-styles.css',
        ),
    ),

`editor_settings` is essentially the 3rd argument to `wp_editor` https://codex.wordpress.org/Function_Reference/wp_editor

**Comment by bfintal** [comment]
I've added the parameter to the site too: http://www.titanframework.net/editor-option/

**Comment by SiamKreative** [comment]
Awesome bro, thanks!
