### ISSUE TITLE
Units in number fields don't work for me

### ISSUE THREAD

**Issue by limestreet** [gambitph/Titan-Framework#227]
I'm using Titan version 1.7.4.
My code (important fields only):
        $headerTab->createOption( array(
            'type' => 'number',
            'unit' => 'px',
	    'id' => 'body_padding_top',
	    'default' => '150',  
            'css' => 'body{padding-top:value;}'
	) );  

In css file I get this (in panel I did set value 44):
body {
  padding-top: 44;
}

I did try with createcss -> but I get the same...
How to use numbers properly?

Thanks in advance

**Comment by limestreet** [comment]
It's working after small change.

	`public function cleanValueForGetting( $value ) {
		if ( $value == '' ) {
			return 0;
		}
		return $value = esc_attr($this->getValue().$this->settings['unit']);
	}`

**Comment by chetzof** [comment]
you should submit a pull request ;)
