### ISSUE TITLE
Generated css contains duplicated declarations

### ISSUE THREAD

**Issue by chetzof** [gambitph/Titan-Framework#232]
```
$titan->createCSS( '
.a {
display: block;
}
' );

```

output
```
.a{display:block;}.a{display:block;}
```

**Comment by drosa88** [comment]
yes, here the same .. :) .. and when i clear all the code in custom css editor, the style still remains..

**Comment by ori** [comment]
Same. In addition it occurs when using color picker with <code>css</code> parameter.

**Comment by coolplektor** [comment]
I will just add that same is happening with javascript (not only with css). If you populate custom js code, it will be written twice on fronted.
