### ISSUE TITLE
Idea: Plugin customizer

### ISSUE THREAD

**Issue by dmgawel** [gambitph/Titan-Framework#237]
Necessity is the mother of invention and this idea comes from necessity.

Problem: I'd like to use WP Customization Panel wchich is familiar to many users to allow them adjust settings (mostly design and content) of my plugin.
My dream solution:
1. Register kind of a 'Custom Customizer'
2. Register fields and sections and assign them to my 'Custom Customizer'
3. Being able to open this customizer in some place of WP admin panel with custom URL to customize (could be set in point 1), for example: http://baseurl.com/shopping-cart/ with all the functionalities of Cutomization API (live changes, fields, etc.), without default WP theme sections and fields.
4. Save settings to option.

What do you think about this idea? I hope it's clear. Could it be integrated into Titan?

**Comment by bfintal** [comment]
1, 2 & 4 are already available.

As for 3 though, I think it can just be as simple as adding a `url` value in your customizer url (e.g. `?url=shopping-cart` to open the page, and then some JS to open the customizer section upon loading and also hide the other sections.

I don't think we can add this though, it's kind of outside the scope of options.

Closing this for now, kindly reopen if needed :)
