### ISSUE TITLE
Support font icons in radio-image option

### ISSUE THREAD

**Issue by chetzof** [gambitph/Titan-Framework#238]
It would be great to have possibility  to use font icons like https://developer.wordpress.org/resource/dashicons/ (and not only) as images for radio options.

Config should look something like this i guess
```
$panel->createOption( array(
    'name' => 'Select a Layout',
    'id' => 'my_layout',
    'type' => 'radio-image',
    'options' => array(
        'grid' => 'dashicons dashicons-grid',
        'list' => 'dashicons dashicons-list'
    ),
    'default' => 'grid',
    'is_font_icon' => true
) );
```

I can provide a PR if needed. Any ideas or suggestions over this feature? I think it makes sense to combine it with `radio-image` option, instead of creating a new one, because they have similar purprose and both represent images basically.

**Comment by ReggieDuran** [comment]
Closed by b62c49d188842024547a9a9293d195c08331123e
