### ISSUE TITLE
website needs an options overview - hard to appraise

### ISSUE THREAD

**Issue by rtpHarry** [gambitph/Titan-Framework#241]
I'm just doing some research to decide which options framework I will adopt for my themes so I'm going through all of the popular option frameworks websites.

Titan looks promising but as somebody completely new to the project I found myself going round in circles on the website looking for some kind of overview. Everywhere you click basically assumes you are already trying to develop with it.

It really needs a visual overview of the framework. For me, I'm interested in:

1. How it integrates into WordPress eg I'm seeing [Options Framework](https://github.com/devinsays/options-framework-plugin) integrates into it in a WP4 style, some look a bit dated, what does yours look like?
2. A list of the options it provides with a screenshot of how it will render eg the CSS editor in [OptionTree](https://wordpress.org/plugins/option-tree/screenshots/) caught my eye.

Just thought I would give you a bit of friendly feedback from a fresh pair of eyes that will hopefully help you attract more users for your framework :)

**Comment by nemke** [comment]
+1

**Comment by bfintal** [comment]
+1 Thanks for the feedback, yes it's a bit hard to see these things since we're always developing with it so an outside view is most of the time forgotten :)

**Comment by bfintal** [comment]
Here ya go: http://www.titanframework.net/what/
