### ISSUE TITLE
Need help with encoding

### ISSUE THREAD

**Issue by goodwinpress** [gambitph/Titan-Framework#242]
Hi, folks,
please help me to solve the problem.

I use Cyrillic alphabet at  the theme options, in the 'name' field, something like this:

 $normalPanel = $adminPanel->createAdminPanel( array(
  'name' => 'Общие настройки ',
) );

For this cause, this options page has url 

site.ru/wp-admin/admin.php?page=themename-Общие настройки

But on some sites this url transform to hexadecimal

and it looks like
 
![screenshot at 07 18-34-18](https://cloud.githubusercontent.com/assets/8179689/7026821/c1b4e086-dd54-11e4-9b16-5948a4e55ac8.png)

So there is no access to the options page. Problem could be solved if i replace Cyrillic to Latin, but this is not the way for me.

May be you know how this can be corrected?
Thanks!

**Comment by goodwinpress** [comment]
i  found the decision - use id at the createAdminPanel options

$normalPanel = $adminPanel->createAdminPanel( array(
'name' => 'Общие настройки ',
'id'=> 'general-options'
) );

voilà!

name displaying in the menu, id using in the url

**Comment by bfintal** [comment]
:) Yup the `id` is auto generated from the name if nothing's given.
