### ISSUE TITLE
Class 'TitanFramework' not found

### ISSUE THREAD

**Issue by TheZoker** [gambitph/Titan-Framework#252]
I have following use:
- main-plugin-file.php
- admin-panel.php
- /tools/tool.php

Now I make a `require_once('admin_panel.php')` and a `require_once('/tools/tool.php')` in the `main-plugin-file.php`

Then I use a `$titan = TitanFramework::getInstance( 'plugin' );` in the `admin-panel.php` to create all options.

Then I use a `$titan = TitanFramework::getInstance( 'plugin' );` in `/tools/tool.php` to get options

But I get a
<pre>Class 'TitanFramework' not found in /wp-content/plugins/plugin-dir/tools/tool.php on line 9</pre>

Can you may help me to solve the issue?
Thank you

**Comment by oherman** [comment]
Can you see if a newer pull from here fixes it? I recall changing detection methods before.

**Comment by bfintal** [comment]
You should create options using the `tf_create_options` hook: http://www.titanframework.net/how
