### ISSUE TITLE
Composer Install Doesn't Work Anymore

### ISSUE THREAD

**Issue by julien731** [gambitph/Titan-Framework#253]
After version 1.7.4 it became impossible to update the framework using Composer. The problem returned by Composer is:

```
gambitph/titan-framework dev-master requires trentrichardson/jquery-timepicker-addon dev-master -> no matching package found
```

Potential causes Composer brings up are:

```
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

It is a really annoying issue that prevents me from updating the framework to the latest version.

**Comment by bfintal** [comment]
I'll just remove it

**Comment by julien731** [comment]
Still having an issue with Composer.

![image](https://cloud.githubusercontent.com/assets/1441024/9625510/f4fa77d0-5180-11e5-96ac-7f778f4a955d.png)
