### ISSUE TITLE
get_terms($taxonomy) shows error.

### ISSUE THREAD

**Issue by neerukoul** [gambitph/Titan-Framework#256]
I want to show my custom taxonomy in "sortable" option array can you please tell me how can i do that.
when i use: get_terms($taxonomy) in code it shows me error:
```
Array
(
    [errors] => Array
        (
            [invalid_taxonomy] => Array
                (
                    [0] => Invalid taxonomy
                )

        )

    [error_data] => Array
        (
        )

)```

**Comment by neerukoul** [comment]
I want this option in admin panel.

**Comment by bfintal** [comment]
You should be able to use `get_terms()` inside the hook `tf_create_options`. Tested this and it should work now in 1.8 (or Github master)

**Comment by serranoabq** [comment]
@bfintal Can you provide an example of how this can be done? I'm running into the same issue. I'm using a custom taxonomy on a custom post type and it seems that Titan starts up before the post type and the taxonomies are available.
