### ISSUE TITLE
Option to hide fields

### ISSUE THREAD

**Issue by ahansson89** [gambitph/Titan-Framework#259]
I have a few options that I would like not to be visible to the user anymore. However, I do not want to remove the option in case that I need the option value again later. An option to hide the fields with CSS would be awesome.

I know I can do this manually, but maybe somebody else could use this feature build into the option arrays? What do you guys think?

**Comment by ardalann** [comment]
If you remove the code that defines those options, does it remove the existing option values from the database?

**Comment by ahansson89** [comment]
It does when you save yes.

**Comment by ardalann** [comment]
I think that needs to change. Titan shouldn't remove the values of an option that's not defined. There could be a method for 'cleaning' Titan's data for that purpose that could be called optionally.

**Comment by ahansson89** [comment]
I am ambivalent about it. There is no need for keeping data that is not needed ever, so I def. do not want to do this for all options, but I do see your point.

**Comment by bfintal** [comment]
I've added a `hidden` argument available for all options. If it's set to `true`, the option won't be shown but it's current value will be retained.

It's helpful for deprecating options which I think is what you are doing @ahansson89

**Comment by bfintal** [comment]
Closing this for now :)
