### ISSUE TITLE
Do we really need Ace?

### ISSUE THREAD

**Issue by ahansson89** [gambitph/Titan-Framework#260]
Titan-Framework is 2.3mb right now where 1.7mb comes from Ace. Do we really need this much extra fluff to support a few option types?

**Comment by alenb** [comment]
Could be replaced by [CodeMirror](https://github.com/codemirror/codemirror) instead?

**Comment by bfintal** [comment]
I've removed the unnecessary files from Ace along with a few others. It's now at 654kb :)

CodeMirror can be an alternative. I really enjoy using it in CodePen.. Although, unless it's broken, let's stick with Ace for now :)
