### ISSUE TITLE
Namespace classes

### ISSUE THREAD

**Issue by ahansson89** [gambitph/Titan-Framework#262]
I just had a bug with the .invisible class used in the sortable option being overwritten by a class setting visibility:hidden;  Namespacing the class will solve this. For backwards compatibility, we should keep the old class.

**Comment by julien731** [comment]
The problem with namespacing the class is that it won't be supported by PHP
5.2

Even though this version is super old, it's still officially supported by
WordPress.

**Comment by ahansson89** [comment]
I am talking about the CSS class here.

**Comment by ahansson89** [comment]
.invisible { //whatever } should be .tf-invisible { //whatever } as some external CSS files can have the class invisible, which is overwriting .invisible.

**Comment by ahansson89** [comment]
https://github.com/gambitph/Titan-Framework/blob/master/class-option-sortable.php

**Comment by julien731** [comment]
Heh. My bad then. I read that too quickly ;)
