### ISSUE TITLE
New Option: Iframe

### ISSUE THREAD

**Issue by gurkankara** [gambitph/Titan-Framework#263]
Hi folks. It was necessary to show an iframe in wp-admin side. Therefore I wrote a new option. I will use it for showing help section. Also If you adding it to Titan Framework I will be very happy. 

class-option-iframe.php
------------------------------------------
<?php
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

class TitanFrameworkOptionIframe extends TitanFrameworkOption {

	/*
	 * Display for options and meta
	 */
	public function display() {
		?>
		<tr valign="top">
		<td colspan="2">
		<h3><?php echo $this->settings['name'] ?></h3>
        <iframe frameborder="0" src="<?php echo $this->settings['url'] ?>" style="width:100%; height:auto; min-height:700px;">
		</td>
		</tr>
		<?php
	}
}
?>

titan-framework.php 
------------------------------------------
add this line -> require_once( TF_PATH . 'class-option-iframe.php' );

using
------------------------------------------
$panel->createOption( array(
	'name'  => 'Iframe',
	'url'  => 'http://yoursite.com/any-page',
	'type'  => 'iframe',
));

**Comment by oherman** [comment]
Sorry for the delay, things are quite busy on our end.

This iFrame... sounds interesting. If you haven't made a pull request yet, please do so in order to consider it for integration.
