### ISSUE TITLE
class-titan-framework.php error upon activating plugin ?

### ISSUE THREAD

**Issue by mentorkadriu** [gambitph/Titan-Framework#264]
I have just downloaded and installed  Underscores &Titan Framework Based Theme.
After  activating this plugin I got this error : 

Warning: preg_match(): Unknown modifier '/' in ```C:\xampp\apps\wordpress\htdocs\wp-content\plugins\titan-framework\class-titan-framework.php``` on line 588
```
if ( ! preg_match( '/^theme_mods_' . $theme . '/', $optionName ) ) {
			return $value;
		}
```
Error is found in Wordpress admin panel -> Plugins -> Installed Plugins

**Comment by oherman** [comment]
Please pull a new copy of titan framework here and see if that fixes it.

**Comment by bfintal** [comment]
This isn't supposed to happen. `$theme` is the current theme name. Anyway, I'll switch it to the less error-prone `strpos`
