### ISSUE TITLE
Framework ignores css/sass lighten

### ISSUE THREAD

**Issue by alenb** [gambitph/Titan-Framework#265]
```
$colourTab->createOption( array(
		'name' => 'Button Main',
		'id' => 'button_main_color',
		'type' => 'color',
		'css' => "
		.btn-theme {
			&.btn-main {
				background-color: \$button_main_color;

				&:hover,
				&:focus {
					background-color: lighten(\$button_main_color, 10%);
				}
			}
		}
		"
	) );
```

For an odd reason it ignores `lighten(\$button_main_color, 10%)`, I'm not to sure as to why though. Hope I'm not doing something incorrectly?

**Comment by ardalann** [comment]
Maybe updating the SCSS compiler would fix this. The newest stable version is 0.0.12 while version 0.0.9 is used in Titan.
http://leafo.net/scssphp/

**Comment by alenb** [comment]
Thank you very kindly for your help. It worked! :)
