### ISSUE TITLE
"Code" field metabox

### ISSUE THREAD

**Issue by peelnet** [gambitph/Titan-Framework#266]
Hi,
I'm not sure if that a bug, but i need it for my personal use. I m using the code field as metabox to add some custom css,It add the generated css into the archive page also and i don't want it there . A option will be nice exanple 'only_singular'=> true. 
For now i fix that by adding thoses line in class-option-code.php at line 115: 
<code>		
if ( ! is_singular() ) {
    return;
}
</code>

**Comment by bfintal** [comment]
You're right `! is_singular()` fixes it. This will be in 1.9 which will be out soon
