### ISSUE TITLE
False Malware detection from Sucuri 

### ISSUE THREAD

**Issue by FirstR-n-R** [gambitph/Titan-Framework#270]
After a server side scan by Sucuri found one of my sites to have Malware, reported to Sucuri, and here is what Sucuri said regarding this issue:

------------------ Sucuri Message -----------------------
I run some tests and scans on your site and didn't find any malware there.

I have fixed the following problem:
require_once(/********/**********/public_html/wp-content/plugins/titan-framework/class-option-gallery.php): failed to open stream: No such file or directory in <b>/********/**********/public_html/wp-content/plugins/titan-framework/titan-framework.php

By commenting this line out from file titan-framework.php
//require_once( TF_PATH . 'class-option-gallery.php' );

I checked older versions of the plugin and also download a fresh version of latest version to compare. 
In all cases the file class-option-gallery.php does not exist.

You might want to contact the developers to find out why the files are missing there.
------------- End Sucuri Message -----------------------------

**Comment by bfintal** [comment]
Thanks for this, the gallery option was removed last minute since it was not yet ready and had some bugs in it #268

**Comment by bfintal** [comment]
This fixes it bd236235d36dc971b385f56b4d685b5400ce4840
