### ISSUE TITLE
Add a Dynamic Welcome Page 

### ISSUE THREAD

**Issue by ahmadawais** [gambitph/Titan-Framework#274]
Just like WordPress welcome page, there can be a dynamic welcome page option. 

Also, the same class can be used to provide developers with a custom admin panel page where they can add whatever HTML/CSS they want.

**Comment by julien731** [comment]
I'm not entirely convinced by this. TF can be used for a wide variety of things and it wouldn't make sense to have a welcome page for themes or small plugins.

Also, creating a welcome page using TF would probably be more complex that creating one yourself as you will need to have a *view* page for the content anyways. The only thing TF could automate is the page registration in the admin menu, but honestly it's only one line if done directly within a plugin.

**Comment by ardalann** [comment]
I completely agree with @julien731
