### ISSUE TITLE
CSS Related Controls

### ISSUE THREAD

**Issue by ahmadawais** [gambitph/Titan-Framework#286]
A good enhancement would be having CSS related controls 

E.g. Padding, Margin, Backgroun etc.

Just like https://docs.reduxframework.com/core/fields/background/ and https://docs.reduxframework.com/core/fields/dimensions/

**Comment by ahmadawais** [comment]
Why I want these is becasue I am unable to render livePreview for CSS properties. 

Take a look at this http://prntscr.com/8gvtme

**Comment by bfintal** [comment]
The `css` attribute should work here. I've been using this in one of our plugins:

    'css' => '#loading-bar-label { margin-left: valuepx; margin-right: valuepx; }'

**Comment by ahmadawais** [comment]
@bfintal Yes, I got that working. But can you look at the links I gave above? Those two options work with "decisions not options" philosophy of WordPress. Instead of creating 4 padding options, I could create one with 4 options inside it.

**Comment by bfintal** [comment]
I agree with that :+1:

**Comment by bfintal** [comment]
Also, just committed 0c6773109cec8081b6ab045b753cfbebace81dfb : the `livePreview` parameter now uses the URL as the value of `value`

**Comment by ahmadawais** [comment]
@bfintal livePreview still not working, can you provide me with a build of master branch or instructions about what to add? I added the two changed files but nada.

**Comment by bfintal** [comment]
Sure, I just updated the zip in dist folder. Or you can also get the whole master zip file and use that in your plugins folder

**Comment by ahmadawais** [comment]
@bfintal  Thanks.
