### ISSUE TITLE
Google fonts list

### ISSUE THREAD

**Issue by sutomo** [gambitph/Titan-Framework#288]
Hi,

I wonder why some fonts on Google fonts selection was not appear on font selection list? Is this issue from Google fonts API?

Thanks,

**Comment by bfintal** [comment]
There's a script in `functions-googlefonts.php` that's used to generate the font list. The list is pre-generated.

But yeah, will need to update soon since it was last updated more than a year ago

**Comment by sutomo** [comment]
Thanks for the update, but just realised all Google fonts weight doesn't carry the styles no higher than 500.

**Comment by ariona** [comment]
Any update on this issue? i didn't see the latest google fonts from the list. Why not using google fonts api to get updated list?
