### ISSUE TITLE
wpColorPicker() error 

### ISSUE THREAD

**Issue by tivnet** [gambitph/Titan-Framework#290]
Please check this out. Thank you!
https://github.com/ThemeAvenue/Awesome-Support/issues/221

**Comment by bfintal** [comment]
@tivnet I've fixed this already, although it's in the https://github.com/gambitph/Titan-Framework/tree/oop-getoption-setoption branch. Will merge it soon.

I'd appreciate it if you guys can use that branch as well to test out whether your options work fine. It has a lot of speed improvements.
