### ISSUE TITLE
On 'Save Changes' in one tab,  reseting values to default in all other tabs

### ISSUE THREAD

**Issue by braankoo** [gambitph/Titan-Framework#292]
Hi guys,

I guess my title describes problem.

I have 5 tabs in admin panel. When I save changes in one tab, all fields in other tabs are back to default values ?
Any ideas ?

Thank you :)

**Comment by bfintal** [comment]
I've tested it with all of our plugins (tested it again just now) and I'm not seeing the problem.

Can you provide some admin code?

**Comment by aanduque** [comment]
I'm having the same issue. In an admin page with multiple tabs, saving options in one tab erase the options from all the others.

**Comment by julien731** [comment]
This is also happening with Awesome Support. I have witnessed it on a client site. However, I can't recreate the problem in my local dev environment.

My guess would be that it's related to the `$_POST` data not passed while saving the options. Looks like TF is getting the default values for options that aren't in the `$_POST`.

**Comment by bfintal** [comment]
This is serious. Worse is that I can't replicate locally nor in any of my sites :(

I've committed a possible fix: b1b1836b4a3c23da3ce7d2d2c834f22b96dc62c5 Can anyone try it out whether this fixes the problem? If it does I will push this out asap.

**Comment by aanduque** [comment]
Hi @bfintal 
For me at least the commit seems to to have solved the issue!
Thank you!

**Comment by bfintal** [comment]
Great! I'm pushing out 1.9.1 now!

**Comment by bfintal** [comment]
1.9.1 released: https://wordpress.org/plugins/titan-framework/

**Comment by cmwwebfx** [comment]
Benjamin, there seems like a huge amount of work you are putting back in to Titan again. What has caused the renewal of energy on this?

**Comment by braankoo** [comment]
everything is cool now :)

:+1: for @bfintal
