### ISSUE TITLE
allow svg files on type="upload"

### ISSUE THREAD

**Issue by EinArzt** [gambitph/Titan-Framework#295]
When using the WP Customizer with an Option with the `type="upload"` you can **not** select any SVG files. Although they are being uploaded and are shown in the Media-Browser, when selecting them nothing happens.
I did enable SVG Support for the Media-Browser.

**Comment by bfintal** [comment]
There's an existing PR on this: #251

It just needs a bit of fixing to match the structural changes with TF :)

**Comment by ReggieDuran** [comment]
db3453ac81a11765e98742ec6da009b195e3d4f7
