### ISSUE TITLE
Number type doesn't refresh

### ISSUE THREAD

**Issue by ahmadawais** [gambitph/Titan-Framework#297]
There is some issue with `number` type option I am not using livepreview but it is not refreshing the page.

**Comment by bfintal** [comment]
Is this the new version? In the new version, if you have a `css` parameter, the css will be recomputed and inserted into the preview without the need for refreshing any more. It compiles the css and injects the changes in. If you have a `livepreview` param, that would be used instead.

**Comment by ahmadawais** [comment]
No I specifically need the page to be reloaded, my plugin has an effect that can only happen during page reload. Yes I am using 1.9.2. And what you are saying make perfect sense. But is it possible for you to add a `transport => refresh` parameter so that if anyone really wants to reload the page he could? 

Coz to solve this issue I had to do something like this https://gist.github.com/ahmadawais/817f7649a414ea975b35#file-class-customizer-php-L372

**Comment by bfintal** [comment]
Let me add a `transport` parameter for all options

**Comment by ahmadawais** [comment]
@bfintal Great Thank you. 
Would you be releasing a minor update or should I download the master?
