### ISSUE TITLE
Preg_match Unknown modifier ‘g’ error

### ISSUE THREAD

**Issue by devmybest** [gambitph/Titan-Framework#306]
I get a warning message whenever a theme name has letter 'g' in it. 
```
Warning: preg_match(): Unknown modifier ‘g’ in public_html/wp-content/plugins/{plugin_name}/includes/titan-framework/class-titan-framework.php on line 597
```
I tried `preg_match_all()` but that was too throws the error.

**Comment by lukehayes** [comment]
I cant replicate this - does it still happen?

**Comment by ReggieDuran** [comment]
Does it still happen @devmybest?
