### ISSUE TITLE
adding hidden attribute to text fields

### ISSUE THREAD

**Issue by oherman** [gambitph/Titan-Framework#307]
Purpose of this is to create variables uneditable to frontend users, but is accessible to the system like a regular variable.

This is akin to the type='hidden' attributes of html text input forms. I encountered a scenario where this is necessary.

**Comment by sebascar** [comment]
This would be really useful. I'm going crazy trying to add hidden variables since the "custom html" doesn't not actually save t the value.

**Comment by ReggieDuran** [comment]
It's already in text option
