### ISSUE TITLE
Slight design change proposal

### ISSUE THREAD

**Issue by ivandotv** [gambitph/Titan-Framework#308]
Currently this is how panel options look.
![screenshot_00220151113 t](https://cloud.githubusercontent.com/assets/390700/11154675/1ebfb1ea-8a41-11e5-9498-5cc0ed72338d.png)

This is the new proposal:
Tabs color is changed, and the gap between tabs and panel is removed.
![screenshot_00120151113 t](https://cloud.githubusercontent.com/assets/390700/11154685/2acfe81a-8a41-11e5-9c2c-e90ca898e377.png)

Not a big change but I think it's for the better.

**Comment by ReggieDuran** [comment]
Thanks for this slight proposal. We've added it right now. 0498522869d1535349ab9bc6b1fbfd6928157e17
