### ISSUE TITLE
Something wrong with current plugin in wordpress repository ?

### ISSUE THREAD

**Issue by ivandotv** [gambitph/Titan-Framework#309]
I've just downloaded generated theme from the titan framework site, and it appears that something
is wrong with the plugin.
The options in the admin are present, and they are getting saved , but when I try to retrieve them in the front-end all I get is `false` for every option (havent tried costumizer)

I have a simple test function in the `functions.php` file.
````php
add_action( 'after_setup_theme', 'myFunction' );

function myFunction() {
	$titan = TitanFramework::getInstance( 'test-titan' );

	$copyright = $titan->getOption( 'copyright' ); //returns "false"

}
````

**Comment by ikixxx** [comment]
Note that if I try to get the code like this.
````php
	$rawOption =get_option('test-titan_options');
````
I get the serialized options, and I see that the `copyright` field is there.

**Comment by screets** [comment]
Hey, probably you need to call your myFunction with "init" action:

    add_action( 'init', 'myFunction' ); 

If it doesn't work, consider to add 10 value as well (that solved our issue):

    add_action( 'init', 'myFunction', 10 );    

Hope it helps!

**Comment by screets** [comment]
Also check here to gather settings without any issue: http://www.titanframework.net/tf_done/
