### ISSUE TITLE
 When you try to update a post from Quick Edit

### ISSUE THREAD

**Issue by eddiewp** [gambitph/Titan-Framework#310]
![captura](https://cloud.githubusercontent.com/assets/7269388/11263967/a5cbffd4-8e5d-11e5-98aa-7ce550cf93dc.PNG)

My code:

$titan = TitanFramework::getInstance( 'enel' );

$postMetaBox = $titan->createMetaBox( array(
	'name'      => 'Destacado',
	'post_type' => 'post',
        'hide_custom_fields' => true
) );

$postMetaBox->createOption( array(
	'name'    => '¿Artículo Destacado?',
	'id'      => 'destacado',
	'type'    => 'enable',
	'default' => false,
) );

**Comment by ReggieDuran** [comment]
hey! @syswperu we tested it out, but we noticed that even with or without titan framework, the message still appeared.
