### ISSUE TITLE
Theme Customizer - Cannot add to existing panels/sections.

### ISSUE THREAD

**Issue by gomarion** [gambitph/Titan-Framework#314]
Hello,

I was trying out Titan Framework for the Theme Customizer feature, but it seems that I can't add to existing sections or panels. Also, is there any way to add a section to the top menu? It seems like it would default to a panel that has no name: http://tinyurl.com/h9lvn2u. I was hoping I could place it just right below the Site Identity section/panel.

Thanks

**Comment by ashtology** [comment]
Hi,
I can't do this too. when i use the names of existing WordPress sections (such as title_tagline or colors) to append options to them, it keep creating new section.
Thanks.

**Comment by payatola2287** [comment]
Hi,
Any updates on this?
I am also trying to put an option in the Site Identity panel in the Theme Customizer.
The documentation, it says to just set the `name` to the panel ID - 'title_tagline','colors', etc. - but nothing shows up in the Theme Customizer.
