### ISSUE TITLE
Metabox values not saving when using it on a CPT

### ISSUE THREAD

**Issue by ghost** [gambitph/Titan-Framework#332]
The Metabox Values are not saving to the options array on Custom Post Types so when I try to display on the front end, I am getting the default values. I took a look at the database and in the options array, there are NONE of my Metabox values. They show up correctly in my Custom Post Types, I can save the values and they show up correctly in the Custom Post Type but they are not saving to the options array in the database. 

Thanks,
Darren

**Comment by otjutt** [comment]
We can't say much without looking at your code.
