### ISSUE TITLE
Documentation:  Append to existing WordPress Customizer sections points to wrong parameter "name"

### ISSUE THREAD

**Issue by MarcusWernicke** [gambitph/Titan-Framework#334]
According to the documentation, the parameter `name` for createThemeCustomizerSection() can also contain the name of an existing section to append that section:

http://www.titanframework.net/docs/theme-customizer-section/

> As of v1.7.1, you can use the names of existing WordPress sections to append options to them. A list of existing WordPress sections: title_tagline, colors, background_image, nav, static_front_page

However, it is in fact the parameter `id` that needs to be used rather than `name` in order to append to an existing section. At least that is the only option that works for me in version 1.9.3 of the plug-in.

createThemeCustomizerSection() also seems to be deprecated according to the code, so I am using createContainer() instead in this example that works:

```
	$section = $titan->createContainer( array(
		'type' => 'customizer',
		'id' => 'title_tagline',
	) );

```

**Comment by carlesstom** [comment]
Thanks so much for this

**Comment by ReggieDuran** [comment]
Thank you for this @MarcusWernicke! We updated the documentation for this :)
