### ISSUE TITLE
PHP Warning:  array_key_exists() 

### ISSUE THREAD

**Issue by goodwinpress** [gambitph/Titan-Framework#336]
Hi friends,

please help, values doesn't save, i look at php_errors log and see:

PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /home/***/titan-framework/lib/class-titan-framework.php on line 265

Line 265 is 

if ( array_key_exists( $optionName, $this->adminOptions ) ) {

I don't understand why array needed (

**Comment by ReggieDuran** [comment]
Hello @goodwinpress! can i see your code?

**Comment by goodwinpress** [comment]
Hi Мr Duran, thank you for answer, this problem already solved.
