### ISSUE TITLE
include_fonts, show_google_fonts, show_websafe fonts have no effect

### ISSUE THREAD

**Issue by lukehayes** [gambitph/Titan-Framework#341]
I am trying to show only a small handful of google fonts in the theme customizer using the include_fonts setting for the font option but It does not change the dropdown list at all.

I have also tried to setting show_google_fonts and show_websafe_fonts to false and it is having no effect at all with all the fonts.

What am I doing wrong?

**Comment by lukehayes** [comment]
I think I have found the problem - I will submit a pull request soon.

**Comment by lukehayes** [comment]
#342 
Here is a pull request if you wanted to check it out.

**Comment by ReggieDuran** [comment]
Closed by c4883c6443672d881dc68879cf2cfbdb5132b03d
