### ISSUE TITLE
Multisite: wrong options when switching blog

### ISSUE THREAD

**Issue by Lugat** [gambitph/Titan-Framework#343]
Hey there,

due to the fact, that the options are preloaded and stored in an instance, the wrong options will be provided when the blog has been switched on a multisite installation.

To avoid this, I added a small but dirty hack.
https://github.com/Lugat/Titan-Framework

There is for sure a better approach to deal with this problem.

Greetings, Lukas

**Comment by ReggieDuran** [comment]
Thanks @Lugat . Can you do a pull request for this?

**Comment by Lugat** [comment]
@ReggieDuran Done.

**Comment by ReggieDuran** [comment]
It's committed now. 2483a259b4dd6a8f14d67fe6dce96a3fe6cda313
