### ISSUE TITLE
Fonts-Preview not working when wp-admin is served over HTTPS

### ISSUE THREAD

**Issue by rockschtar** [gambitph/Titan-Framework#344]
File: /lib/iframe-font-preview.php
Line: 105

`printf( "<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=%s:400,%s.....`

The URL-Scheme should be changed to "//", otherwise the font preview is not working because the google webfont stylesheet url is blocked by the browser.

![blocked](https://cloud.githubusercontent.com/assets/87191/16533786/7c3134c0-3fdb-11e6-9106-d42825e24c24.PNG)

**Comment by ReggieDuran** [comment]
4303cd6fadef2d523d64389aab98b8dc11aac0d8 Thanks for this @rockschtar!
