### ISSUE TITLE
Wordpress Media upload gets broken when plugin is active

### ISSUE THREAD

**Issue by damianmuti** [gambitph/Titan-Framework#348]
Just as the title says, when the plugin is active, Wordpress Media Upload feature gets broken. When i deactivate it, everythings back to normal.
I've search for this issue and it seems that it used to happen in the past and it got fixed, but for some reason is still buggy for me.

My environment:
- WAMP server (PHP 5.5.12).
- Windows 10
- Wordpress 4.5.3.
- Latest version of Titan Framework.
- Magic Fields (Plugin)
- Advanced Custom Fields (Plugin).

Tried deactivating every plugin and only activating Titan Framework, but issue persists. Also tried with Wordpress hosted version and the one in this repo.

Any help will be appreciated :)

**Comment by ReggieDuran** [comment]
@damianmuti, Is this problem of yours still exist?
