### ISSUE TITLE
Upgrade scssphp to latest version for PHP 7 compatibility

### ISSUE THREAD

**Issue by sc0ttkclark** [gambitph/Titan-Framework#349]
The latest versions have PHP 7 compatibility:

https://github.com/leafo/scssphp/releases/tag/v0.6.5

The offending issue is usage of `$this->string()` and `function string` as that is a reserved word in PHP 7.

**Comment by ReggieDuran** [comment]
6923cdc71750a0ba08607dd34d4e2050815479c4 We upgraded our scss library using jetpack's scssphp file but we can't remove 5.2 because it may cause lots of errors.
