### ISSUE TITLE
PHP7 Compatibility

### ISSUE THREAD

**Issue by julien731** [gambitph/Titan-Framework#353]
It seems that the TItan Framework is not compatible with PHP7. [As reported here](https://github.com/Awesome-Support/Awesome-Support/issues/334), there are a couple of issues with the framework.

With PHP7 being stable and its adoption rate going up, I believe making sure TF is compatible is an important task. The unit tests should also be ran against PHP7 in Travis CI.

**Comment by bfintal** [comment]
Possible fix, this is the same scssphp script used by Jetpack, only namespaced: https://gist.github.com/bfintal/60f303db3c6c3f27002d72ed45947dcb
