### ISSUE TITLE
Options Multilanguage support (WPML)

### ISSUE THREAD

**Issue by ArchimidisM** [gambitph/Titan-Framework#355]
Thanks a lot for this great plugin.
However I have a question. I have 2 text fields in my options page, which I would like to translate their outputs using the WPML plugin.

For example the WPML provides some documentation to translate extra options here
https://wpml.org/documentation/support/language-configuration-files/
But I am not sure whether that is applicable to the TitanFramework.

Are the option values multilanguage support or not?
Thanks again for this great plugin.

**Comment by ReggieDuran** [comment]
Good day @ArchimidisM. Titan option values doesn't support multi-language.

**Comment by ArchimidisM** [comment]
Thanks a lot for your answer.

**Comment by Lugat** [comment]
I'm simply extending Titan and overwriting the getInstance method to make it work with WMPL

```
  abstract class Titan extends \TitanFramework
  {
    
    public static function getInstance($optionNamespace)
    {
      
      if (defined('ICL_LANGUAGE_CODE')) {
        $optionNamespace .= '_'.ICL_LANGUAGE_CODE;
      }
      
      return parent::getInstance($optionNamespace);
      
    }
    
  }
```
