### ISSUE TITLE
Problem with non-english language

### ISSUE THREAD

**Issue by amin3d** [gambitph/Titan-Framework#362]
In the name of Allah,Hi, My language is Persian, when I wanted to save the setting page, I faced with the page which said you have not enough permission to see this page. I think because of using Persian name in the createAdminPanel I faced with this problem. My suggestion is to use id which has a English name and use name just to show to the user, tanks

**Comment by ReggieDuran** [comment]
8be95092dc6c60d5f63eb71f6448f2b2565781a5 @amin3d, We've merged your pr and also tried to tested it. Let us know if your problem will be fix.
