### ISSUE TITLE
WARNING MESSAGES

### ISSUE THREAD

**Issue by rogerad** [gambitph/Titan-Framework#364]
i am using your code and get this message

Warning: array_merge(): Argument #2 is not an array in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\titan-framework\lib\class-option-font.php on line 541

How do i disable warning messages so the user does not see them ?

**Comment by ReggieDuran** [comment]
@rogerad Please paste the code that caused the error.

**Comment by rogerad** [comment]
here is the editor code
$aa_panel->createOption( array(

		'id'   => 'aa_editor_type', // The ID which will be used to get the value of this option
		'type' => 'editor', // Type of option we are creating
		'name' => 'My Editor Option', // Name of the option which will be displayed in the admin panel
		'desc' => 'This is our option' // Description of the option which will be displayed in the admin panel

	) );

i am using version 1.10 of titan
 screenshot attached
![screenshot - 1_10_2016 11_26_32 pm](https://cloud.githubusercontent.com/assets/18638656`/19014385/ed3b47c8-882e-11e6-818c-2a7eeb524954.png)`

**Comment by ReggieDuran** [comment]
@rogerad. We've tested your code and there's no error. Can you send another screenshot?

**Comment by rogerad** [comment]
SAME SCREENSHOT

![screenshot - 1_10_2016 11_26_32 pm](https://cloud.githubusercontent.com/assets/18638656/19071980/86722956-8a7e-11e6-9219-46194a8e3a9d.png)

**Comment by ReggieDuran** [comment]
Update now @rogerad 19fde9add13e602ffbb02e58a9094568c8cfe433. This commit will fix your problem now.
