### ISSUE TITLE
IMAGE NOT ALIGNED CORRECTLY IN EDITOR

### ISSUE THREAD

**Issue by rogerad** [gambitph/Titan-Framework#365]
editor is good but alignment of image inserted in editor is not working.

it APPEARS to be working correctly, BUT when viewed AFTER the editor has been saved , then the image is ALWAYS on the RIGHT side

**Comment by ReggieDuran** [comment]
@rogerad Do you have the latest version of titan framework? Because we have tested your problem and we find out that there's nothing wrong. The image is on the left side after saving.

**Comment by rogerad** [comment]
hi
 i am using version 1.10 from wordpress site 
 I will post code later

**Comment by rogerad** [comment]
its working now
