### ISSUE TITLE
admin-ajax.php with a status of 403

### ISSUE THREAD

**Issue by askaria** [gambitph/Titan-Framework#385]
Hello.

When I createMetabox and write 'post_type' => 'post' http://prntscr.com/du9uwg 
admin-ajax in admin pages dont work: http://prntscr.com/du9tyg 

Sorry for my English

**Comment by bfintal** [comment]
Confirmed. Adding a meta box:

	$test = $titan->createMetaBox( array(
		'name' => 'test',
		'post_type' => 'post',
	));

And saving a post quick edit resulted in a 403 error in the call to admin-ajax.php

**Comment by diviengine** [comment]
Is this resolved as I am still having this issue?

**Comment by rob006** [comment]
@diviengine Seems like issue was fixed, but not yet released.

@bfintal Can you tag new release? `1.12.1` mas released 9 months ago, it would be great to have new release with this bugfix.

**Comment by diviengine** [comment]
@bfintal please :D
