### ISSUE TITLE
Option type editor: more-tag not working

### ISSUE THREAD

**Issue by davidsneighbour** [gambitph/Titan-Framework#393]
I think it would make sense to remove the short-tag button for the more-link in the editor option (`<!--more-->`). 

![selection_012](https://cloud.githubusercontent.com/assets/83281/24358417/39b8a834-132b-11e7-93e5-c12c1cc69729.png)

It is impossible to create a link to an option as an existing page on a website, so this tag is more or less unusable on options. it should be hidden on options (on text and visual editor views).

**Comment by bfintal** [comment]
We can use this: https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/class-wp-editor.php#L345

Use the filter to remove the `more` button in `$qtInit['buttons']`
