### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by andrastudio** [gambitph/Titan-Framework#401]
Is Titan stop being developed? It's been 8 months since last update.
Hope to see Titan Framework still being developed because it's such a great option framework.

**Comment by mikedamoiseau** [comment]
I was wondering the same.. I might have to switch to CMB2 for my project, which is quite a pain as I really like Titan Framework.

**Comment by galengidman** [comment]
Kinda wondering the same thing. Big fan of Titan, but the lack of recent contribution is concerning. No hard feelings to the dev — obviously a big project like this would take a lot of time and effort to maintain. I hope that if the original dev no longer has time to maintain, they'll try to find a good maintainer — this is too good of a project to let die!

**Comment by bfintal** [comment]
Just released an update a few weeks ago, now WP 4.9 compatible finally. Thanks for understanding! :)

**Comment by codeclinic** [comment]
Is it dead again? I noticed issues are being closed without any publicly acknowledged solution. Also, its been a long time since the last update.

**Comment by galengidman** [comment]
@codeclinic - I'm moving my plugin to CMB2
