### ISSUE TITLE
Date option default expects timestamp, docs state Y-m-d formatted string

### ISSUE THREAD

**Issue by AaronOverton** [gambitph/Titan-Framework#408]
This works:

    $tab->createOption([
        'name' => 'Report Date',
        'id' => 'hidden-report-date',
        'type' => 'date',
        'default' => time()
    ]);

This does not:

    $tab->createOption([
        'name' => 'Report Date',
        'id' => 'hidden-report-date',
        'type' => 'date',
        'default' => date('Y-m-d')
    ]);

Documentation example is `'default' => '2010-12-20',`, found here: http://www.titanframework.net/docs/date/

Using the documented technique for a default always produces a date of 1970-01-01 (timestamp 0).

**Comment by mrjk990** [comment]
you must use date function like this
```
$tab->createOption([
    'name' => 'Report Date',
    'id' => 'hidden-report-date',
    'type' => 'date',
    'default' => date('Y-m-d', time())
]);
```

**Comment by tojibon** [comment]
This pull request has the support for that date format default input with a couple of other update.
https://github.com/gambitph/Titan-Framework/pull/410

**Comment by bfintal** [comment]
@tojibon Can you resubmit the PR for the date issue only?
