### ISSUE TITLE
undefined js function for number option

### ISSUE THREAD

**Issue by majick777** [gambitph/Titan-Framework#412]
I'm getting undefined function _ in line 124 of /lib/class-option-number.php:
`$( '.tf-number input[type=number]' ).on( 'keyup', _.debounce( function() {`
perhaps this debounce function part of the underscores library ?

**Comment by bfintal** [comment]
Yup it's part of the underscores library which is already enqueued.

I'll need more info please :)

**Comment by majick777** [comment]
Cannot seem to reproduce this, guess it must have been a network glitch or conflict with another plugin.
