### ISSUE TITLE
Gallery Field

### ISSUE THREAD

**Issue by RafaelOlivra** [gambitph/Titan-Framework#45]
I wonder why is so hard to find a framework that include it by default.
I have a lot of clients who I needed to add a Gallery custom post type to make it easy for them to add new albums, and I need a separate field just for the main gallery itself, because ask them to use 'add media -> create gallery' and also add the description together on the editor, confuses 99% of them :)

It also can be useful if we want a scrolling gallery section on any place like the homepage for example :)

May you guys consider this? Thanks :)

**Comment by tojibon** [comment]
If you want you can have a look on the rep with <code>gallery</code> option and <code>separator</code> option  here https://github.com/tojibon/Titan-Framework 

What you need is just copy both file on your plugin folder and include them on specific file 
Another way would be, directly clone my repository as It is currently using the latest version of Titan-Framework.

The only missing feature is no ordering feature available yet.

Thanks

**Comment by sandrodz** [comment]
Great work @tojibon 

@bfintal would it be possible to include this in original repo?

**Comment by ReggieDuran** [comment]
http://www.titanframework.net/docs/gallery/
