### ISSUE TITLE
Feature request: $titan->setOption()

### ISSUE THREAD

**Issue by violacase** [gambitph/Titan-Framework#94]
For all kind of purposes it would be nice if $titan->getOption() also had a brother  $titan-><em>set</em>Option( )

NOTA: with this option I could for instance easy realize #72, #77

**Comment by codeclinic** [comment]
I really need to set an option outside of the options admin panel (eg programmatically). Can someone give me a bit more info on how to use setOption(). Ive tried the following but without success:

**Comment by shohag121** [comment]
Hey, 
I want to save the changed value for an option from other function of my plugin.
When using `setOption()` and setting new value; I'm getting the new value (using getOption() ) for that titan instance only but it's not saving the value in the database permanently. When recalling the value from another page, it just returns the default value.

Currently, I'm doing:
`$titan = TitanFramework::getInstance('my-plugin');`
`$color =  $titan->getOption('theme-color')`
Getting `$color` value **red.**
`$titan->setOption('theme-color', 'Green')`
`$color =  $titan->getOption('theme-color')`
Getting `$color` value **Green**.

### But On other page:

`$titan = TitanFramework::getInstance('my-plugin');`
`$color =  $titan->getOption('theme-color')`
Getting `$color` value still **red**.

What am I missing here?

Thanks.

**Comment by RobertoAyala2112** [comment]
@shohag121 same problem here!

@bfintal can you tell us how to save the option after setOption() ?

**Comment by shohag121** [comment]
@matgargano Can you please help?

**Comment by matgargano** [comment]
@shohag121 I stopped using this project years ago. Advanced custom fields pro accomplishes everything it does and more.
